function Export-HtmlReport {
    <#
    .SYNOPSIS
        Generates a local HTML report of scored job results.
    .DESCRIPTION
        Creates a standalone HTML file with all scored jobs grouped by bucket
        (Apply Today, Worth Looking, Lower Priority). Serves as both a local
        reference and a fallback when email notifications fail.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [array]$AllScoredJobs,

        [Parameter(Mandatory)]
        [string]$OutputPath
    )

    $applyJobs = $AllScoredJobs | Where-Object { $_.Bucket -eq "apply_today" } | Sort-Object { $_.Score } -Descending
    $reviewJobs = $AllScoredJobs | Where-Object { $_.Bucket -eq "worth_looking" } | Sort-Object { $_.Score } -Descending
    $skipJobs = $AllScoredJobs | Where-Object { $_.Bucket -eq "skip" -or $_.Bucket -eq "review" -or $_.Bucket -eq "unscored" } | Sort-Object { $_.Score } -Descending

    $buildSection = {
        param($jobs, $sectionTitle, $color)
        if ($jobs.Count -eq 0) { return "" }
        $html = "<h2 style='color: $color; border-bottom: 2px solid $color; padding-bottom: 8px;'>$sectionTitle ($($jobs.Count))</h2>"
        foreach ($j in $jobs) {
            $html += @"
<div style="padding: 12px; margin: 8px 0; background: #f9f9f9; border-radius: 6px; border-left: 4px solid $color;">
    <strong><a href="$($j.Url)">$($j.Title)</a></strong> — $($j.Company) | Score: <strong>$($j.Score)</strong><br>
    <span style="color: #666;">$($j.Location) | $($j.Source) | Salary: $($j.SalaryEstimate)</span><br>
    <span style="font-size: 13px;">$($j.ScoreReason)</span><br>
    <span style="font-size: 12px; color: #888;">Skills: $($j.SkillsMatched)</span>
</div>
"@
        }
        return $html
    }

    $html = @"
<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Job Hunter Report - $(Get-Date -Format 'yyyy-MM-dd')</title>
<style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; }
    a { color: #2980b9; text-decoration: none; }
    a:hover { text-decoration: underline; }
</style>
</head>
<body>
<h1>🎯 Job Hunter Report — $(Get-Date -Format 'MMMM d, yyyy')</h1>
<p>Total scored: $($AllScoredJobs.Count) | Apply Today: $($applyJobs.Count) | Worth Looking: $($reviewJobs.Count) | Skip: $($skipJobs.Count)</p>
$(& $buildSection $applyJobs "🚀 Apply Today (85+)" "#2ecc71")
$(& $buildSection $reviewJobs "👀 Worth Looking (70-84)" "#f39c12")
$(& $buildSection $skipJobs "⏭️ Lower Priority (<70)" "#95a5a6")
<footer style="margin-top: 30px; padding-top: 15px; border-top: 1px solid #eee; color: #999; font-size: 12px;">
    Generated by Job Hunter | $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
</footer>
</body></html>
"@

    $html | Set-Content -Path $OutputPath -Encoding UTF8
    Write-Host "📄 HTML report saved: $OutputPath" -ForegroundColor Cyan
}
