function Send-JobNotification {
    <#
    .SYNOPSIS
        Prepares and saves a job notification email for sending via Gmail MCP.
    .DESCRIPTION
        Builds an HTML email with the "Apply Today" bucket jobs and saves it
        as a JSON payload file. The email is sent via the Google Workspace MCP
        integration when running through Kiro, or can be sent manually.

        The payload file is saved to: data/pending_email.json
        Format: { subject, to, body_html, generated_at }
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [array]$Jobs,

        [Parameter(Mandatory)]
        [hashtable]$NotificationConfig,

        [int]$TotalJobsFound = 0,
        [int]$NewJobsFound = 0
    )

    if (-not $NotificationConfig.enabled) {
        Write-Verbose "Notifications disabled, skipping"
        return
    }

    if ($Jobs.Count -eq 0) {
        Write-Verbose "No high-score jobs to notify about"
        return
    }

    $gmailAddress = $NotificationConfig.gmail_address

    # Build HTML email body
    $jobRows = ""
    foreach ($job in $Jobs) {
        $scoreColor = if ($job.Score -ge 90) { "#2ecc71" } elseif ($job.Score -ge 85) { "#27ae60" } else { "#f39c12" }
        $jobRows += @"
        <tr style="border-bottom: 1px solid #eee;">
            <td style="padding: 12px;">
                <strong><a href="$($job.Url)" style="color: #2980b9; text-decoration: none;">$($job.Title)</a></strong><br>
                <span style="color: #666;">$($job.Company) | $($job.Source)</span><br>
                <span style="color: #888; font-size: 12px;">$($job.Location)</span>
            </td>
            <td style="padding: 12px; text-align: center;">
                <span style="background-color: $scoreColor; color: white; padding: 4px 12px; border-radius: 12px; font-weight: bold;">$($job.Score)</span>
            </td>
            <td style="padding: 12px; font-size: 13px;">$($job.ScoreReason)</td>
            <td style="padding: 12px; font-size: 12px; color: #666;">$($job.SkillsMatched)</td>
            <td style="padding: 12px; font-size: 13px;">$($job.SalaryEstimate)</td>
        </tr>
"@
    }

    $htmlBody = @"
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px;">
    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px; margin-bottom: 20px;">
        <h1 style="color: white; margin: 0;">Job Hunter - Apply Today</h1>
        <p style="color: rgba(255,255,255,0.9); margin: 10px 0 0 0;">
            $(Get-Date -Format "MMMM d, yyyy") | $($Jobs.Count) high-match jobs found | $NewJobsFound new listings scanned
        </p>
    </div>

    <div style="background: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
        <strong>Run Summary:</strong> Scanned $TotalJobsFound total listings, $NewJobsFound new, <strong>$($Jobs.Count) scored 85+</strong>
    </div>

    <table style="width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
        <thead>
            <tr style="background: #34495e; color: white;">
                <th style="padding: 12px; text-align: left;">Position</th>
                <th style="padding: 12px; text-align: center;">Score</th>
                <th style="padding: 12px; text-align: left;">Why</th>
                <th style="padding: 12px; text-align: left;">Skills Match</th>
                <th style="padding: 12px; text-align: left;">Salary Est.</th>
            </tr>
        </thead>
        <tbody>
            $jobRows
        </tbody>
    </table>

    <div style="margin-top: 20px; padding: 15px; background: #e8f8f5; border-radius: 8px; border-left: 4px solid #2ecc71;">
        <strong>Tip:</strong> Jobs scored 85+ are strong matches for your Principal SRE profile. Apply within 48 hours of posting for best results.
    </div>

    <p style="color: #999; font-size: 12px; margin-top: 30px;">
        Generated by Job Hunter | Powered by PowerShell + LLM Scoring<br>
        To adjust scoring, edit config.json profile section.
    </p>
</body>
</html>
"@

    $subject = "Job Hunter: $($Jobs.Count) High-Match SRE Roles Found - $(Get-Date -Format 'MMM d')"

    # Save email payload for MCP sending
    $payload = @{
        subject      = $subject
        to           = $gmailAddress
        from         = $gmailAddress
        body_html    = $htmlBody
        generated_at = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
        job_count    = $Jobs.Count
    }

    $payloadPath = Join-Path (Split-Path $PSScriptRoot -Parent) "data\pending_email.json"
    $dataDir = Split-Path $payloadPath -Parent
    if (-not (Test-Path $dataDir)) {
        New-Item -ItemType Directory -Path $dataDir -Force | Out-Null
    }

    $payload | ConvertTo-Json -Depth 3 | Set-Content -Path $payloadPath -Encoding UTF8
    Write-Host "  Email payload saved: $payloadPath" -ForegroundColor Cyan
    Write-Host "  Ready to send via Gmail MCP to: $gmailAddress" -ForegroundColor Green
}
