<#
.SYNOPSIS
    Sends the pending job notification email via Gmail MCP.
.DESCRIPTION
    Reads the pending email payload generated by Run-JobHunter.ps1 and
    displays it for sending through Kiro's Google Workspace MCP integration.

    Usage: Ask Kiro to "send the pending job hunter email" or run this script
    to see what's queued.
#>

[CmdletBinding()]
param()

$payloadPath = "$PSScriptRoot\data\pending_email.json"

if (-not (Test-Path $payloadPath)) {
    Write-Host "No pending email found. Run Run-JobHunter.ps1 first." -ForegroundColor Yellow
    exit 0
}

$payload = Get-Content -Path $payloadPath -Raw | ConvertFrom-Json

Write-Host "`nPending Email:" -ForegroundColor Cyan
Write-Host "  To:      $($payload.to)" -ForegroundColor White
Write-Host "  Subject: $($payload.subject)" -ForegroundColor White
Write-Host "  Jobs:    $($payload.job_count)" -ForegroundColor White
Write-Host "  Created: $($payload.generated_at)" -ForegroundColor Gray
Write-Host "`nTo send: ask Kiro to 'send the pending job hunter email'" -ForegroundColor Green
Write-Host "The email will be sent via your Gmail ($($payload.to)) using the Google Workspace MCP.`n" -ForegroundColor DarkGray
